Repository bcgov/sso-switchover-agent, pull requests merged in 2023-09, with the labels that each got.

#126 fix: update packages to resolve dependabot alerts
  poetry.lock
  pyproject.toml
Labels: enhancement

#128 chore: revert the limit creation
  transition-scripts/values/values.yaml
Labels: enhancement

#127 feat: deploy changes to production
  .github/release.yml
  .github/workflows/create-release.yml
  .github/workflows/publish-image.yml
  Dockerfile
  docs/developer-docs.md
  docs/environment-variables.md
  helm/values-e4ca1d-local.yaml
  poetry.lock
  pyproject.toml
  src/clients/dns.py
  src/config.py
  src/logic.py
  transition-scripts/helpers/helm.sh
  transition-scripts/values/values-gold-e4ca1d-dev-active.yaml
  transition-scripts/values/values-gold-e4ca1d-dev-standby.yaml
  transition-scripts/values/values-gold-e4ca1d-prod-active.yaml
  transition-scripts/values/values-gold-e4ca1d-prod-standby.yaml
  transition-scripts/values/values-gold-e4ca1d-test-active.yaml
  transition-scripts/values/values-gold-e4ca1d-test-standby.yaml
  transition-scripts/values/values-golddr-e4ca1d-dev-active.yaml
  transition-scripts/values/values-golddr-e4ca1d-dev-standby.yaml
  transition-scripts/values/values-golddr-e4ca1d-prod-active.yaml
  transition-scripts/values/values-golddr-e4ca1d-prod-standby.yaml
  transition-scripts/values/values-golddr-e4ca1d-test-active.yaml
  transition-scripts/values/values-golddr-e4ca1d-test-standby.yaml
Labels: release:minor

#129 feat: updated permissions to write-all for publish image action
  .github/workflows/publish-image.yml
Labels: bug

#130 chore: release
  .github/workflows/publish-image.yml
Labels: release:minor

#132 chore: release
  .github/workflows/publish-image.yml
Labels: release:minor

#134 fix: add exception handling to css maintenance
  src/logic.py
Labels: enhancement
